[workspace]

members = [
    "add_and_search_words-211",
    "reverse-linked-list-206",
    "valid-parentheses-20",
    "kth-largest-element-in-an-array-215",
    "course-schedule-207",
    "happy-number-202",
    "word-search-ii-212",
]
