[package]
name = "add_and_search_words-211"
version = "0.1.0"
authors = ["lck"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
